matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc-5
      addons:
        apt:
          packages:
            - gcc-5
            - g++-5
          sources:
            - ubuntu-toolchain-r-test
      env:
        - _CC=gcc-5
        - _CXX=g++-5
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang
      addons:
        apt:
          packages:
            - libstdc++-5-dev
          sources:
            - ubuntu-toolchain-r-test
    - os: osx
      sudo: false
      compiler: clang
before_install:
  - echo "before install"
  - brew --version
  - brew install
  - brew install boost
install:
  - echo "install"
before_script:
  - echo "before script"
language: cpp
script:
  - echo "script"
  - if [ -n "$_CC" ]; then export CC=$_CC; fi
  - if [ -n "$_CXX" ]; then export CXX=$_CXX; fi
  - env
  - cat .travis.yml
  - $CC --version
  - $CXX --version
  - $CXX foo.cpp -std=c++11
notifications:
  email: false
