matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc-5
      addons:
        apt:
          packages:
            - gcc-5
            - g++-5
          sources:
            - ubuntu-toolchain-r-test
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang
      addons:
        apt:
          packages:
            - gcc-5
            - g++-5
          sources:
            - ubuntu-toolchain-r-test
    - os: osx
      sudo: false
      compiler: clang
language: cpp
script:
  - cat .travis.yml
  - uname -a
  - echo /usr/bin/g++-*
  - c++ --version
  - echo $CC
  - echo $CXX
  - $CXX --version
  - c++ foo.cpp -std=c++11
  - g++-5 foo.cpp -std=c++11
  - clang++ foo.cpp -std=c++11
notifications:
  email: false
