matrix:
  include:
    - os: osx
      sudo: false
      compiler: gcc
      env:
        - _CC=gcc-5
        - _CXX=g++-5
    - os: osx
      sudo: false
      compiler: clang
before_install:
  - echo "before install"
  - brew update
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$_CC" == "gcc-"* ]]; then brew install "${_CC/-/@}"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$_CC" == "gcc-"* ]]; then
      echo "Ayyy!!"
    fi
install:
  - echo "install"
before_script:
  - echo "before script"
language: cpp
script:
  - echo "script"
  - env
  - if [ -n "$_CC" ]; then export CC=$_CC; fi
  - if [ -n "$_CXX" ]; then export CXX=$_CXX; fi
  - env
  - cat .travis.yml
  - $CC --version
  - $CXX --version
  - $CXX foo.cpp -std=c++11
  - ./a.out
notifications:
  email: false
