matrix:
  include:
    - os: osx
      sudo: false
      compiler: gcc
    - os: osx
      sudo: false
      compiler: clang
before_install:
  - echo "before install"
  - brew update
  - brew install boost
install:
  - echo "install"
before_script:
  - echo "before script"
language: cpp
script:
  - echo "script"
  - if [ -n "$_CC" ]; then export CC=$_CC; fi
  - if [ -n "$_CXX" ]; then export CXX=$_CXX; fi
  - env
  - cat .travis.yml
  - $CC --version
  - $CXX --version
  - $CXX foo.cpp -std=c++11
notifications:
  email: false
