matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc-5
      addons:
        apt:
          packages:
            - gcc-5
            - g++-5
          sources:
            - ubuntu-toolchain-r-test
      env:
        - CC=gcc-5
        - CXX=g++-5
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang
    - os: osx
      sudo: false
      compiler: clang
language: cpp
script:
  - cat .travis.yml
  - $CC --version
  - $CXX --version
  - $CXX foo.cpp -std=c++11
notifications:
  email: false
