matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      compiler: gcc
    - os: linux
      dist: trusty
      sudo: required
      compiler: clang
    - os: osx
      sudo: false
      compiler: clang
language: cpp
script:
  - uname -a
  - c++ --version
