matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
    - os: linux
      compiler: clang
    - os: osx
      compiler: clang
language: cpp
script:
  - uname -a
  - c++ --version
sudo: false
